const billsModel = require("../models/billsModel");
const returnModel = require("../models/returnModel");
const inventoryModel = require("../models/InventoryModels");
const customerModel = require("../models/customerModel");
const moment = require("moment-timezone");




const getCustomer = async (req, res) => {
  try {
const bills = await customerModel.find({});

    res.json(bills);
  } catch (error) {
    console.error("Error fetching customer:", error);
    res.status(500).send("Server Error");
  }
};

// Update customer notes
const updateCustomerNotes = async (req, res) => {
  const { id } = req.params;
  const { notes } = req.body;

  try {
    const customer = await customerModel.findById(id);
    if (!customer) {
      return res.status(404).send("Customer not found");
    }

    customer.notes = notes;
    await customer.save();

    res.send("Notes updated successfully");
  } catch (error) {
    console.error("Error updating notes:", error);
    res.status(500).send("Something went wrong");
  }
};



const addCustomer = async (req, res) => {
  try {
   console.log(req.body);
    const { name, phone } = req.body;

    console.log(req.body + " name"+ name + " phone" + phone);

    // Basic validation
    if (!name || !phone) {
      return res.status(400).json({ error: "Name and phone are required." });
    }

    // Check if customer already exists
    const existingCustomer = await customerModel.findOne({ phone });
    if (existingCustomer) {
      return res.status(409).json({ error: "Customer already exists." });
    }

    // Save new customer
    const newCustomer = new customerModel(req.body);
    await newCustomer.save();

    res.status(201).json({ message: "Customer added successfully.", customer: newCustomer });
  } catch (error) {
    console.error("Error adding customer:", error);
    res.status(500).json({ error: "Internal server error." });
  }
};



  //add items
const addBillsController = async (req, res) => {
  try {
  console.log(req.body);
    const newBill = new billsModel(req.body);
    await newBill.save();

     const { cartItems, subTotal, totalAmount, userId } = req.body;

      // Process each cart item in the sale
         for (const cartItem of cartItems) {
           let remainingQty = cartItem.quantity; // quantity sold for this item
           // Find all inventory records for the code, ordered by oldest first
           const inventories = await inventoryModel.find({ code: cartItem.code, quantity: { $gt: 0 } }).sort({ createdAt: 1 });

           // Iterate over inventory records and reduce quantity FIFO
           for (let inv of inventories) {
             if (remainingQty <= 0) break;
             if (inv.quantity >= remainingQty) {
               // If inventory record can cover the remaining quantity, subtract it and finish
               inv.quantity -= remainingQty;
               remainingQty = 0;
               console.log(" Available in stock ", cartItem.code);
               await inv.save();
             } else {
               // Not enough in this record, deplete it and reduce remaining quantity
               remainingQty -= inv.quantity;
               inv.quantity = 0;
               console.log(" Not enough in stock making it 0", cartItem.code);
               await inv.save();
             }
           }
           // If remainingQty is still > 0 (either because no inventory was found or insufficient stock),
           // create a new inventory record with negative quantity.
           if (remainingQty > 0) {
            console.log("Creating negative inventory please rectify", cartItem.code);
             await Inventory.create({
               code: cartItem.code,
               price: cartItem.price,  // you can choose to record the sale price
               quantity: -remainingQty,
                invoiceNumber: "Autogenerated",
             });
           }
         }

    res.send("Bill Created Successfully!");
  } catch (error) {
    res.send("something went wrong");
    console.log(error);
  }
};
const getBillsController = async (req, res) => {
  try {
    const { date } = req.query; // "2025-02-25"
    console.log("Query Date (IST):", date);

    // Parse the provided date in IST without conversion to UTC
    const start = moment.tz(date, "YYYY-MM-DD", "Asia/Kolkata").startOf("day").toDate();
    const end = moment.tz(date, "YYYY-MM-DD", "Asia/Kolkata").endOf("day").toDate();

    console.log("Querying MongoDB from:", start, "to", end);

    const bills = await billsModel.find({
      date: { $gte: start, $lte: end },
    });

    console.log("Bills for selected date:", bills);
    res.json(bills);
  } catch (error) {
    console.error("Error fetching bills:", error);
    res.status(500).send("Server Error");
  }
};

const addReturnsController = async (req, res) => {
  try {
    console.log(req.body);

    const { creditNote } = req.body;
    if (!creditNote) {
      return res.status(400).send("Credit Note Number is required");
    }

    // Replace or insert the document (upsert = true)
    await returnModel.findOneAndUpdate(
      { _id: creditNote  },
      req.body,
      { upsert: true, new: true }
    );

    res.send("Return saved/replaced successfully!");
  } catch (error) {
    console.error("Error saving return: ", error);
    res.status(500).send("Something went wrong");
  }
};


const getTotalMonthlySales = async (req, res) => {
  try {
    const { date } = req.query; // Expecting 'YYYY-MM' format

     console.log(date);

    // Validate the input date format
    if (!moment(date, 'YYYY-MM', true).isValid()) {
      return res.status(400).json({ error: 'Invalid date format. Expected YYYY-MM.' });
    }

    // Parse the input date
    const inputDate = moment.tz(date, 'YYYY-MM', 'Asia/Kolkata');

    // Determine the start of the month and the current date
    const startOfMonth = inputDate.clone().startOf('month').toDate();
    const today = moment.tz('Asia/Kolkata').toDate();

    // Ensure the end date doesn't exceed today's date
    const endDate = inputDate.isSame(moment(), 'month') ? today : inputDate.clone().endOf('month').toDate();

    // Aggregate total sales up to the endDate
    const result = await billsModel.aggregate([
      {
        $match: {
          date: {
            $gte: startOfMonth,
            $lte: endDate,
          },
        },
      },
      {
        $group: {
          _id: null,
          totalSales: { $sum: '$totalAmount' },
        },
      },
    ]);

    // Extract total sales from the aggregation result
    const totalSales = result.length > 0 ? result[0].totalSales : 0;

    // Calculate the number of days elapsed in the month up to endDate
    const daysElapsed = moment(endDate).date();

    // Calculate average daily sales
    const averageDailySales = totalSales / daysElapsed;

    // Respond with the total and average daily sales
    res.json({ totalSales, averageDailySales });
  } catch (error) {
    console.error('Error calculating total sales:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

const getDailySalesByCategory = async (req, res) => {
 try {
    const { month } = req.query; // Expecting 'YYYY-MM' format

   console.log("Month"+req.query);
   console.log(month);
    // Validate the input date format
    if (!moment(month, 'YYYY-MM', true).isValid()) {
      return res.status(400).json({ error: 'Invalid date format. Expected YYYY-MM.' });
    }

    // Parse the input month
    const inputDate = moment.tz(month, 'YYYY-MM', 'Asia/Kolkata');

   console.log("Input Date"+inputDate);
    // Determine the start and end of the month
    const startOfMonth = inputDate.clone().startOf('month').toDate();
    const endOfMonth = inputDate.clone().endOf('month').toDate();

    console.log("Start" + startOfMonth + " End of month " + endOfMonth);
const salesData = await billsModel.aggregate([
  {
    $match: { date: { $gte: startOfMonth, $lte: endOfMonth } }
  },
  {
    $unwind: '$cartItems'
  },
  {
    $group: {
      _id: {
        category: '$cartItems.category',
        day: { $dayOfMonth: '$date' }
      },
      totalSales: {
        $sum: {
          $multiply: [
            { $ifNull: ['$cartItems.price', 0] },
            { $ifNull: ['$cartItems.quantity', 0] }
          ]
        }
      },
    },
  },
  {
    $sort: { '_id.day': 1 }  // ✅ Sort by day ascending
  },
  {
    $group: {
      _id: '$_id.category',
      totalAmount: { $sum: '$totalSales' }, // ✅ Total sales for hover
      dailySales: {
        $push: { day: '$_id.day', totalSales: '$totalSales' }
      },
    },
  },
  {
    $project: {
      _id: 0,
      category: '$_id',
      dailySales: 1,
      totalAmount: 1  // ✅ Include totalAmount for UI tooltip/hover
    }
  },
]);



 console.log("Response : " + salesData);
    res.json(salesData);
  } catch (error) {
    console.error('Error fetching daily sales by category:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};


const getTop20SalesItems = async (req, res) => {
  try {
    const { category, month } = req.query;

    console.log("Received Month Query:", month);

    if (!moment(month, 'YYYY-MM', true).isValid()) {
      return res.status(400).json({ error: 'Invalid date format. Expected YYYY-MM.' });
    }

    const inputDate = moment.tz(month, 'YYYY-MM', 'Asia/Kolkata');
    const startOfMonth = inputDate.clone().startOf('month').toDate();
    const endOfMonth = inputDate.clone().endOf('month').toDate();

    console.log("Start:", startOfMonth, "End:", endOfMonth);

    const topProducts = await billsModel.aggregate([
      { $match: { date: { $gte: startOfMonth, $lt: endOfMonth }, "cartItems.category": category } },
      { $unwind: "$cartItems" },
      { $match: { "cartItems.category": category } },
      {
        $group: {
          _id: "$cartItems.name",
          totalSold: { $sum: "$cartItems.quantity" },
          totalSales: { $sum: { $multiply: ["$cartItems.quantity", "$cartItems.price"] } }
        }
      },
      { $sort: { totalSales: -1 } },
      { $limit: 20 }
    ]);

    if (!Array.isArray(topProducts)) {
      console.error("Unexpected Response Format:", topProducts);
      return res.json([]); // Return an empty array if data is not in expected format
    }

console.log("Top 20 Products Response:", JSON.stringify(topProducts, null, 2));
    res.json("Top products"+ topProducts);
  } catch (error) {
    console.error('Error fetching top sales items:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
};

module.exports = {
  addBillsController,
  getBillsController,
  addReturnsController,
  addCustomer,
  getCustomer,
  updateCustomerNotes,
  getTotalMonthlySales,
  getDailySalesByCategory,
  getTop20SalesItems,
};